name: Build docker-etl

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-docker-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: docker-etl:build
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Code
        run: |
          docker run docker-etl:build /bin/bash -c \
          "python -m pytest docker_etl/ tests/; \
          flake8 docker_etl/ tests/;\
          black docker_etl/ tests/"

      - name: Verify jobs have required files
        run: docker run docker-etl:build script/verify_files

      - name: Verify CI config is up-to-date
        run: docker run docker-etl:build python3 -m docker_etl.ci_config --dry-run --gha | diff -B .github/workflows/jobs.yml -
